### ISSUE TITLE
Paper consultation

### ISSUE THREAD

**Issue by Mrsheng173** [EsratMaria/Reinforcement-Learning_for_Energy_Minimization_Using_CLoudsim#3]
Hello, I would like to ask if the code can run out of the rendering in the paper?

**Comment by EsratMaria** [comment]
Hello, thanks for reaching out, but I am afraid I am not quite sure what do you mean! Can you be a little specific?

**Comment by Mrsheng173** [comment]
Can the existing code run out of the picture above?
















At 2021-09-23 16:41:41, "Esrat Maria" ***@***.***> wrote:

Hello, thanks for reaching out, but I am afraid I am not quite sure what do you mean! Can you be a little specific?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by EsratMaria** [comment]
I think it should as long as you stick to the basic idea of RL, It's not limited to the Cloud.
